name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: check test & lint
        uses: actions/setup-node@v1
      - run: make install
      - run: make lint
      # - name: Test & publish code coverage
      #   uses: paambaati/codeclimate-action@v2.6.0
      #   env:
      #     CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      #   with:
      #     coverageCommand: make test-coverage

